---
name: "Documentation: terraform-docs"

on:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render documentation and push changes back to branch
        uses: terraform-docs/gh-actions@v0.11.0
        with:
          config-file: ".terraform-docs.yml"
          git-push: "true"

      - name: Render documentation for `basic` example and push changes back to branch
        uses: terraform-docs/gh-actions@v0.11.0
        with:
          config-file: "../../.terraform-docs.yml"
          git-push: "true"
          working-directory: "./examples/basic"
