---
name: "Security Scan: tfsec"

on:
  pull_request:

jobs:
  tfsec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # see https://aquasecurity.github.io/tfsec/v0.63.1/getting-started/configuration/github-actions/github-action/
      - name: Lint Code with tfsec
        uses: aquasecurity/tfsec-sarif-action@master
        with:
          config_file: tfsec.yml
          sarif_file: tfsec.sarif

      # see https://github.com/github/codeql-action/tree/main/upload-sarif
      - name: Upload tfsec results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: tfsec.sarif
